name: netwalk_flutter
description: netwalk

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the Icons class.
  uses-material-design: true

  assets:
    - assets/Off.png
    - assets/OffBottom.png
    - assets/OffBottomTop.png
    - assets/OffLeft.png
    - assets/OffLeftBottom.png
    - assets/OffLeftBottomTop.png
    - assets/OffLeftRight.png
    - assets/OffLeftRightBottom.png
    - assets/OffLeftRightBottomTop.png
    - assets/OffLeftRightTop.png
    - assets/OffLeftTop.png
    - assets/OffRight.png
    - assets/OffRightBottom.png
    - assets/OffRightBottomTop.png
    - assets/OffRightTop.png
    - assets/OffTop.png
    - assets/On.png
    - assets/OnBottom.png
    - assets/OnBottomTop.png
    - assets/OnLeft.png
    - assets/OnLeftBottom.png
    - assets/OnLeftBottomTop.png
    - assets/OnLeftRight.png
    - assets/OnLeftRightBottom.png
    - assets/OnLeftRightBottomTop.png
    - assets/OnLeftRightTop.png
    - assets/OnLeftTop.png
    - assets/OnRight.png
    - assets/OnRightBottom.png
    - assets/OnRightBottomTop.png
    - assets/OnRightTop.png
    - assets/OnTop.png
    - assets/ServerOnBottom.png
    - assets/ServerOnBottomTop.png
    - assets/ServerOnLeft.png
    - assets/ServerOnLeftBottom.png
    - assets/ServerOnLeftBottomTop.png
    - assets/ServerOnLeftRight.png
    - assets/ServerOnLeftRightBottom.png
    - assets/ServerOnLeftRightBottomTop.png
    - assets/ServerOnLeftRightTop.png
    - assets/ServerOnLeftTop.png
    - assets/ServerOnRight.png
    - assets/ServerOnRightBottom.png
    - assets/ServerOnRightBottomTop.png
    - assets/ServerOnRightTop.png
    - assets/ServerOnTop.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/
  
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
